---
- hosts: windows
  tasks:
  - name: Create directory structure
    win_file:
      path: C:\MSSQL2019
      state: directory

  - name: Copy File
    win_copy:
      src: '/var/lib/jenkins/workspace/SQL2019/setupfiles/'
      dest: C:\MSSQL2019\
      remote_src: no

  - name: Run remote PowerShell Script
    win_command: powershell.exe -ExecutionPolicy ByPass -File C:\MSSQL2019\sqlconfig.ps1 -vvv
        
        
        
